---
grafana_oauth_client_id: "grafana"
grafana_backup_enabled: false
grafana_backup_schedule: "*-*-* 03:00:00"
grafana_backup_remotes: []
oauth2proxy_oauth_client_id: "oauth2proxy"
metrics_write_user: "metrics"
dex_local_admin: false
dex_github: false
