namespace: beyondallreason
name: monitoring
description: Minimal BAR monitoring galaxy collection to allow importing client role easily
version: 0.0.1
readme: README.md
authors:
  - BAR Team
dependencies:
  "victoriametrics.cluster": "==2.50.4"
  "prometheus.prometheus": "==0.30.0"
