---
domain_name_dex: "infraid.beyondallreason.dev"
domain_name_grafana: "grafana.beyondallreason.dev"
domain_name_victoriametrics: "metrics.beyondallreason.dev"
domain_name_victorialogs: "logs.beyondallreason.dev"
metrics_write_password: "{{ vault_metrics_write_password }}"
logs_write_password: "{{ vault_logs_write_password }}"
dex_github: true
github_org: "beyond-all-reason"
github_client_id: "{{ vault_github_client_id }}"
github_client_secret: "{{ vault_github_client_secret }}"
victoriametrics_web_allowed_admin: "allowed_groups=beyond-all-reason:monitoring-admins"
victoriametrics_web_allowed_editor: "allowed_groups=beyond-all-reason:monitoring-admins,beyond-all-reason:monitoring-editors"
victorialogs_web_allowed_admin: "{{ victoriametrics_web_allowed_admin }}"
victorialogs_web_allowed_editor: "{{ victoriametrics_web_allowed_editor }}"
grafana_role_attribute_path: "contains(groups[*], 'beyond-all-reason:monitoring-admins') && 'Admin' || contains(groups[*], 'beyond-all-reason:monitoring-editors') && 'Editor' || contains(groups[*], 'beyond-all-reason:monitoring-viewers') && 'Viewer' || 'None'"
monitoring_write_instance_dev: false # for the client role
monitoring_metrics_write_password: "{{ vault_metrics_write_password_raw }}"
monitoring_logs_write_password: "{{ vault_logs_write_password_raw }}"
grafana_backup_enabled: true
grafana_backup_schedule: "0/8:00"
grafana_backup_remotes:
  - name: primary
    path: "{{ vault_grafana_backup_primary_path }}"
    rclone_config: |
      type = gcs
      service_account_file = /etc/rclone/primary.json
      no_check_bucket = true
      bucket_policy_only = true
    credentials_file_content: "{{ vault_grafana_backup_primary_credentials }}"
