---
domain_name_dex: "id.bar-mon.local"
domain_name_grafana: "grafana.bar-mon.local"
domain_name_victoriametrics: "metrics.bar-mon.local"
domain_name_victorialogs: "logs.bar-mon.local"
metrics_write_password: "$2y$14$kzhgGvaDcRZwAKY5uZZVquOedyYXgPyJ66CejiHkuH5S6Km/jwY5K" # "metrics"
logs_write_password: "$2a$14$gKPMKK8VGzFFrAcvCd0Of.pjmcc6fvE2tYmP4l4IrpoaLHmA9nROO" # "logs"
victoriametrics_web_allowed: "allowed_emails=admin@local"
victoriametrics_web_allowed_admin: "{{ victoriametrics_web_allowed }}"
victoriametrics_web_allowed_editor: "{{ victoriametrics_web_allowed }}"
victorialogs_web_allowed: "allowed_emails=admin@local"
victorialogs_web_allowed_admin: "{{ victorialogs_web_allowed }}"
victorialogs_web_allowed_editor: "{{ victorialogs_web_allowed }}"
grafana_role_attribute_path: "email == 'admin@local' && 'Admin' || 'None'"
dex_local_admin: true
dex_local_admin_password: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W" # "password"
monitoring_write_instance_dev: true # for the client role
monitoring_metrics_write_host_ip: "127.0.0.1"
monitoring_logs_write_host_ip: "127.0.0.1"
